spring.application.name=blogApp

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=anchal
spring.datasource.password=changemeinprod!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Security
jwt.secret=qpmS7Y4ldsB5HWK6I3bXFaGWq8gyoTd+qjZwSIOOqAQ=
